# Generated by Django 5.2 on 2025-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('tone', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('suggested_action', models.JSONField()),
            ],
        ),
    ]
